### ISSUE TITLE
Organize code into a python-package friendly structure 

### ISSUE THREAD

**Issue by ktarbet** [HydrologicEngineeringCenter/hec-dss-python#18]

**Comment by FlowMatric** [comment]
@ktarbet, I recently built a few python packages to help with automating HEC-RAS. As part of that I just cloned this repo to see if it could replace the platform dependent [pyhecdss](https://github.com/gyanz/pydsstools) package. One of my first task items is to enable some basic package management and then do some testing. 

I'd be happy to contribute to this repo/issue but at this point still need to get the basic project to run [^1]. I'd usually use poetry and sphinx for some documentation. In fact I often start a package using the [Hypermodern Python](https://github.com/cjolowicz/cookiecutter-hypermodern-python) cookiecutter template which comes with a lot of tools for test automation, building of the package and it's documentation, linting, etc. Does that sound like something you may appreciate for this package as well? Alternatively one could of course keep it lean or simply disable the tools that are not wanted.

[^1]: With respect to this I was wondering if the shared binaries are not part of the repo on purpose. I looked for them in my local installations and online and it seems somewhat difficult to find them. Having to compile them myself (presumably from [here](https://github.com/HydrologicEngineeringCenter/hec-dss)) is IMO somewhat prohibitive. Maybe the README could  benefit from some advice on where to find them if including them in the repo is not possible?

**Comment by ktarbet** [comment]
@FlowMatric Thanks for trying out the hec-dss-python repo.     Note the functionality is just getting started with regular interval time-series as the first supported data type.

To run the project the platform specific shared library is needed (hecdss.dll or libhecdss.so).   We likely need to install the gfortran library as a dependency on Linux.       In windows I've just copied hecdss.dll to the same directory as the code.

There is a linux(.so) and Windows(dll)  here: https://github.com/HydrologicEngineeringCenter/hec-dss-python/releases/tag/v0.0.1-alpha   

The binaries are also in a Nexus repository: https://www.hec.usace.army.mil/nexus/#browse/search=keyword%3Dhecdss%20AND%20version%3D7-IS*

I dream that the method/process that builds a package, could pull a specific version of the shared binaries as part of the build. So the hec-dss-python library and hec-dss dependency can be versioned together.

Contributions would be great!  @jeffsuperglide was assigned/planning to look at this issue (packaging), so let's see what he says to avoid two peoples work colliding.

**Comment by FlowMatric** [comment]
@ktarbet, thanks for the links! I did go through the Nexus repo before but never realized that the maven repo holds binaries besides all the java libraries. Good to know it's there! 

For now I just added the relevant libraries to a lib folder and am trying figure out how `ctypes.cdll` can locate them reliably when the package is installed (via pip).

@jeffsuperglide , I did pull main and for my own convenience started re-structuring it. As I mentioned in my earlier comment, I am using poetry for managing (development) dependencies (i.e. _Flake8_ for style guide enforcement and _black_ for code formatting).  Please let me know if you are interested in my changes or if I should create a PR so we can discuss.

**Comment by jeffsuperglide** [comment]
@FlowMatric
Not sure how much time, if any, I can dedicate to this project.  Suggested dev tools are fine.  I have not seen much standards in the federal government while developing applications.  I hope that that is something to change (in my shop) soon.  I will be pushing Pylint, Black and Setuptools for Python with the understanding that sometimes other dev tools may need to be considered.  I do prefer that Cython used to create extensions from the DSS base code and not using the `ctypes` builtin.  It may work up until it gets too complicated, but that's my opinion.

**Comment by FlowMatric** [comment]
OK to close?
