### ISSUE TITLE
TimeSeries.pathname vs Timeseries.dsspath

### ISSUE THREAD

**Issue by FlowMatric** [HydrologicEngineeringCenter/hec-dss-python#24]
@ktarbet  I am not sure but it seems as if this should use the TimeSeries.dsspath attribute?

https://github.com/HydrologicEngineeringCenter/hec-dss-python/blob/fcee841201a3ee24bec6750c644bfce434ed51d0/src/hecdss/hec_dss.py#L93C25-L93C25

**Comment by ktarbet** [comment]
I agree!  good catch.

In test_basics, the line below,  will also need to be updated.

```python
tsc.pathname = "//SACRAMENTO/PRECIP-INC//1Day/OBS-modified/"
dss.put(tsc)
```
