### ISSUE TITLE
migration path from version 6 dss files to version 7

### ISSUE THREAD

**Issue by dwr-psandhu** [HydrologicEngineeringCenter/hec-dss-python#60]
There is no support for version 6 dss files, so what is the recommended way to move to version 7 files from existing version 6 files?

**Comment by oskarhurst** [comment]
The recommended technique for converting between dss 6 to dss 7 is using our standalone application DSS-Vue.
https://www.hec.usace.army.mil/software/hec-dssvue/

@ktarbet - feel free to add more context

**Comment by dwr-psandhu** [comment]
I guess a scripting approach would be to use the jython in hecdssvue then. Thanks

**Comment by oskarhurst** [comment]
There is actually a built in tool under the tools tab that will automatically convert to your choses version of DSS

**Comment by dwr-psandhu** [comment]
@oskarhurst I prefer scripting solutions rather than having to click around on UIs. So I am looking for a script or a command line tool to help convert. Thanks

**Comment by perrymanmd** [comment]
To script it in jython you would use `hec.heclib.dss.HecDSSUtilitiesconvertVersion(String fileName)`.
You can see it used at line 1032 of https://github.com/HydrologicEngineeringCenter/DSSVue-Example-Scripts/blob/master/src/DssConverter.py
